import { Stats } from "./stats";
import { Feature } from "./feature";
import { Proficiencies } from "./proficiencies";
import { DamageType } from "./damage";
import { Speed } from "./speed";
import { ChoiceGroup } from "./choices";

export type Size = "Tiny" | "Small" | "Medium" | "Large" | "Huge";

/**
 * The subset of Species fields a single ChoiceOption may write to. Layered
 * onto a Species via `applyPatch` (utils/species.ts).
 *
 * Merge semantics:
 *   - resistances / languages: appended (de-duped via Set)
 *   - speed: per-key shallow merge (patch wins per key)
 *   - abilityScoreIncreases: per-stat addition (NOT overwrite)
 *   - features: shallow overlay by feature name; partial fields overwrite
 */
export interface SpeciesPatch {
  resistances?: DamageType[];
  speed?: Partial<Speed>;
  abilityScoreIncreases?: Partial<Stats>;
  languages?: string[];
  features?: Record<string, Partial<Feature>>;
}

/**
 * A species (5e 2024 terminology for what older books called "race").
 * Generated by scripts/convertspecies.ts from 5etools data.
 *
 * Anything that requires the player to make a creation-time choice lives in
 * `choices` — there is no separate `abilityChoices` / `languageChoices` /
 * `resistanceChoices` field. The runtime resolver in utils/species.ts walks
 * `choices` once and applies each picked option's patch.
 */
export interface Species {
  name: string;
  source: string;
  size: Size;
  speed: Speed;
  abilityScoreIncreases: Partial<Stats>;
  features: Record<string, Feature>;
  languages: Set<string>;
  proficiencies?: Partial<Proficiencies>;
  resistances?: DamageType[];
  choices?: ChoiceGroup[];
  subspecies?: Record<string, Subspecies>;
}

//
export type Subspecies = { name: string; source: string } & Partial<
  Omit<Species, "name" | "source" | "subspecies">
>;
