import { Stats } from "./stats";
import { Feature } from "./feature";
import { Proficiencies } from "./proficiencies";
import { DamageType } from "./damage";
import { Speed } from "./speed";

export type Size = "Tiny" | "Small" | "Medium" | "Large" | "Huge";

/**
 * The subset of Species fields a single ChoiceOption may write to. Layered
 * onto a Species via `applyPatch` (utils/species.ts).
 *
 * Merge semantics:
 *   - resistances / languages: appended (de-duped via Set)
 *   - speed: per-key shallow merge (patch wins per key)
 *   - abilityScoreIncreases: per-stat addition (NOT overwrite)
 *   - features: shallow overlay by feature name; partial fields overwrite
 */
export interface SpeciesPatch {
	resistances?: DamageType[];
	speed?: Partial<Speed>;
	abilityScoreIncreases?: Partial<Stats>;
	languages?: string[];
	features?: Record<string, Partial<Feature>>;
}

/** One picker option presented to the player at character creation. */
export interface ChoiceOption {
	id: string;
	label: string;
	apply: SpeciesPatch;
}

/**
 * A named group of player-resolved picks. Every species choice lives here:
 * ability bumps, language picks, resistance picks, draconic ancestry, etc.
 *
 *   - `count` is how many distinct options must be picked (default 1).
 *   - `unique` defaults to true: the same option can't be picked twice in a
 *     multi-pick group.
 */
export interface ChoiceGroup {
	id: string;
	name: string;
	count?: number;
	unique?: boolean;
	options: ChoiceOption[];
}

/**
 * A species (5e 2024 terminology for what older books called "race").
 * Generated by scripts/convertspecies.ts from 5etools data.
 *
 * Anything that requires the player to make a creation-time choice lives in
 * `choices` — there is no separate `abilityChoices` / `languageChoices` /
 * `resistanceChoices` field. The runtime resolver in utils/species.ts walks
 * `choices` once and applies each picked option's patch.
 */
export interface Species {
	name: string;
	source: string;
	size: Size;
	speed: Speed;
	abilityScoreIncreases: Partial<Stats>;
	features: Record<string, Feature>;
	languages: Set<string>;
	proficiencies?: Partial<Proficiencies>;
	resistances?: DamageType[];
	choices?: ChoiceGroup[];
	subspecies?: Record<string, Subspecies>;
}

// 
export type Subspecies = { name: string; source: string } & Partial<
	Omit<Species, "name" | "source" | "subspecies">
>;
